In [1]:
import os
import glob

from lxml import etree
from bs4 import BeautifulSoup
from parsel import Selector

import pandas as pd
import numpy as np
import json

import regex as re

import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
pio.renderers.default = "vscode"

In [2]:
# with open('john-hole.html') as fp:
#     soup = BeautifulSoup(fp, 'html.parser')
with open('hole-htmls/john-hole-jul3.html') as f:
    html1 = f.read()

In [3]:
def create_df_from_html(html):
    html = html.replace('<b>', '')
    html = html.replace('</b>', '')
    html = html.replace('\n', '')

    selector = Selector(html)

    message_objs = {
        'texts' : [],
        'image' : [],
        'video' : [],
        'sender_number' : [],
        'reactions' : []
    }
    dates = []
    for message in selector.xpath('//div[@class="message"]'):
        dates.append(re.sub(r'\(.*\)', '', message.xpath('./div/p/span[@class="timestamp"]/text()').get()))
        message_objs['sender_number'].append(message.xpath('./div/p/span[@class="sender"]/text()').get())
        message_objs['texts'].append(message.xpath('./div/div/span[@class="bubble"]/text()').get())
        message_objs['image'].append(message.xpath('.//div/div/div[@class="attachment"]/img/@src').get())
        message_objs['video'].append(message.xpath('.//div/div/div[@class="attachment"]/video/source/@src').get())
        reactions = message.xpath('./div/div[@class="tapbacks"]').xpath('./div[@class="tapback"]/span/text()').getall()
        message_objs['reactions'].append([reaction.replace('\t', '') for reaction in reactions])


    print(f"Number of Messages: {len(message_objs['texts'])}")
    
    message_objs['dates'] = dates
    return pd.DataFrame(message_objs)

In [4]:
df = create_df_from_html(html1)
# df2 = create_df_from_html(html2)

Number of Messages: 3628

In [5]:
# df = pd.concat([df1, df2])

In [6]:
df.texts = df.texts.str.strip()
df.dates = df.dates.str.strip()
df.image = df.image.str.strip()
df.video = df.video.str.strip()
df.sender_number = df.sender_number.str.strip()

In [7]:
# df.set_index('dates', inplace=True)

In [8]:
df.dates = pd.to_datetime(df.dates, format="%b %d, %Y %I:%M:%S %p")

In [9]:
# Dropping duplicates
df = df.drop_duplicates(subset=['sender_number', 'dates'])

In [10]:
df

,texts,image,video,sender_number,reactions,dates
0,Igor you legit do fuck all bro wake up,None,None,+16138588921,[Laughed by ryan.matson@icloud.com],2025-06-03 08:03:02
1,None,attachments/301/57215.jpeg,None,+16133559273,"[Laughed by +16138588921, Loved by +1416305426...",2025-06-03 08:11:22
2,throwback to the good ol days,attachments/301/57218.jpg,None,+14163054266,[Laughed by +16138588921],2025-06-03 08:44:58
3,None,attachments/301/57219.jpeg,None,+16133559273,[],2025-06-03 09:07:33
4,did you cop me any,None,None,+16134004076,[],2025-06-03 09:08:37
...,...,...,...,...,...,...
3623,Ryan is driving me 800km,None,None,+14169857677,[Laughed by +16133559273],2025-07-03 14:03:47
3624,Riley’s face card got Ryan driving 800km,None,None,+16133559273,[],2025-07-03 14:05:58
3625,"Hey Siri, play cousins by kanye west",None,None,+16133559273,[],2025-07-03 14:06:30
3626,Ryans gonna see these messages and turn right ...,None,None,+16133559273,[],2025-07-03 14:08:10
3627,igor what’s your PR on adult friends finder,None,None,+16134004076,[],2025-07-03 14:09:12

In [11]:
# df.to_json("test.json", orient="records")

In [12]:
df.set_index('dates', inplace=True)

In [13]:
df = df.loc[df.index.month == 6] # ensures only june

In [14]:
df.sender_number.unique()

array(['+16138588921', '+16133559273', '+14163054266', '+16134004076',
       '+15198782573', '+16133160960', 'ryan.matson@icloud.com',
       '+16048685587', 'itsjaxonmusic@gmail.com', '+14167995612',
       '+14169857677', '+16136202840', '+16137628867', 'Me',
       '+16476226650', 'gregorynip@icloud.com', '+16132612783',
       '+16138758948', '+436764425651', '+16139797154',
       'edenkettleson@gmail.com', '+16138044084',
       'hashtagyoloswagbeef@gmail.com'], dtype=object)

In [15]:
senders = {
    '+16138044084' : 'Ryan',
    'ryan.matson@icloud.com' : 'Ryan',
    '+16472994537' : 'Greg',
    '+16476226650' : 'Ali',
    '+15198782573' : 'John',
    '+14168347529' : 'Tommy',
    '+14383514096' : 'Jake',
    '+16138588921' : 'Ben',
    'ben_maycock@yahoo.com' : 'Ben',
    '+16048685587' : 'Michaela',
    '+19024973878' : 'Ryan 2',
    'ryan.keays@gmail.com' : 'Ryan 2',
    'darcydrums@yahoo.ca' : 'Darcy',
    '+447918720754' : 'Darcy',
    '+16136202840' : 'Darcy',
    'Me' : 'Henry',
    '+16474679692' : 'Pias',
    '+16133160960' : 'Jack',
    'itsjaxonmusic@gmail.com' : 'Jack',
    '+436764425651' : 'Miklos',
    '+14167055056' : 'Ernesto',
    '+14168368964' : 'Rayhan',
    '+12263763043' : 'Maggie',
    '+14169857677' : 'Riley',
    '+14372341484' : 'M****',
    '+14372555533' : 'Colin',
    'ernestormz99@gmail.com' : 'Ernesto',
    '+16133559273' : 'Igor',
    '+16475754548' : 'Nicole',
    '+16137628867' : 'Mel',
    'melaniesmyth13@gmail.com' : 'Mel',
    'gregorynip@icloud.com' : 'Greg', 
    'edenkettleson@gmail.com' : 'Eden',
    '+12368865666' : 'Eden',
    '+16474591137' : 'Krystiana',
    '+14163054266' : 'Austin',
    'ryanmatson18@gmail.com' : 'Ryan',
    '+16134004076' : 'Nick',
    '+14167995612' : 'Mack',
    '+16139797154' : 'Dan'
}

In [16]:
df['reactions_received'] = df['reactions'].apply(lambda x : len(x))

/var/folders/zm/kglhp53x58752bpgh6114_f40000gn/T/ipykernel_4337/1268291554.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
df['reactions_received']

dates
2025-06-03 08:03:02    1
2025-06-03 08:11:22    4
2025-06-03 08:44:58    1
2025-06-03 09:07:33    0
2025-06-03 09:08:37    0
                      ..
2025-06-30 22:45:50    1
2025-06-30 22:51:31    0
2025-06-30 22:52:02    4
2025-06-30 23:14:02    1
2025-06-30 23:14:29    1
Name: reactions_received, Length: 2750, dtype: int64

In [18]:
df['sender'] = df['sender_number'].replace(senders)

/var/folders/zm/kglhp53x58752bpgh6114_f40000gn/T/ipykernel_4337/1599837386.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [19]:
text_count = df.groupby('sender').count().sort_values(by='texts', ascending=False)

In [20]:
text_count['reactions_received'] = df.groupby('sender').sum()['reactions_received']

In [21]:
text_count['messages'] = text_count['texts'] + text_count['image'] + text_count['video']
text_count = text_count.sort_values(by='messages', ascending=False)

In [22]:
# Tommy reacted but did not send any messages

# tommy_dict = [{col: 0 for col in text_count.columns}]
# tommy_dict[0]['sender'] = 'Tommy'
# tommy_df = pd.DataFrame(tommy_dict)
# tommy_df = tommy_df.set_index('sender')
# text_count = pd.concat([text_count, tommy_df])

In [23]:
text_count[['texts', 'image', 'messages']]

                               texts  image  messages
sender
Igor                             653     77       732
Ryan                             305     64       371
Ben                              300     25       330
+16132612783                     215     33       249
Jack                             205     20       226
Austin                           147     23       171
John                              78     69       151
Nick                             120     11       132
Darcy                             95      9       105
Mack                              86     10        96
Riley                             59      5        64
Greg                              14      3        18
Henry                             13      1        14
Dan                                9      0         9
hashtagyoloswagbeef@gmail.com      6      0         6
Michaela                           5      0         5
Mel                                3      0         3
+16138758948                       2      1         3
Miklos                             2      0         2
Eden                               1      0         2
Ali                                1      0         1

In [24]:
text_count['reactions_sent'] = pd.Series()
text_count['reactions_sent'] = text_count['reactions_sent'].fillna(0)

/var/folders/zm/kglhp53x58752bpgh6114_f40000gn/T/ipykernel_4337/1290227952.py:2: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [25]:
text_count['hahas_sent'] = pd.Series()
text_count['hahas_sent'] = text_count['hahas_sent'].fillna(0)

/var/folders/zm/kglhp53x58752bpgh6114_f40000gn/T/ipykernel_4337/2859609646.py:2: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [26]:
def reactions_sent(x):
  for reaction in x:
    for sender in df.sender_number.unique():
      if sender in reaction:
        try:
          text_count.loc[senders.get(sender, sender), 'reactions_sent'] += 1
        except KeyError:
          pass

In [27]:
def hahas_sent(x):
  for reaction in x:
    for sender in df.sender_number.unique():
      if (sender in reaction) and ("Laughed" in reaction):
        try:
          text_count.loc[senders.get(sender, sender), 'hahas_sent'] += 1
        except KeyError:
          pass

In [28]:
df['reactions'].apply(reactions_sent)
df['reactions'].apply(hahas_sent)

dates
2025-06-03 08:03:02    None
2025-06-03 08:11:22    None
2025-06-03 08:44:58    None
2025-06-03 09:07:33    None
2025-06-03 09:08:37    None
                       ...
2025-06-30 22:45:50    None
2025-06-30 22:51:31    None
2025-06-30 22:52:02    None
2025-06-30 23:14:02    None
2025-06-30 23:14:29    None
Name: reactions, Length: 2750, dtype: object

In [29]:
text_count[['texts', 'image', 'reactions_received', 'reactions_sent', 'hahas_sent', 'messages']]

,texts,image,reactions_received,reactions_sent,hahas_sent,messages
sender,,,,,,
Igor,653,77,463,191,170,732
Ryan,305,64,356,202,187,371
Ben,300,25,192,260,234,330
+16132612783,215,33,127,28,12,249
Jack,205,20,165,309,294,226
Austin,147,23,117,71,60,171
John,78,69,136,16,13,151
Nick,120,11,49,180,167,132
Darcy,95,9,61,277,264,105
Mack,86,10,35,48,31,96
Riley,59,5,22,57,49,64
Greg,14,3,19,4,2,18
Henry,13,1,14,55,45,14
Dan,9,0,5,31,31,9
hashtagyoloswagbeef@gmail.com,6,0,0,0,0,6
Michaela,5,0,1,18,16,5
Mel,3,0,1,10,8,3
+16138758948,2,1,9,8,6,3
Miklos,2,0,2,0,0,2
Eden,1,0,3,1,0,2
Ali,1,0,0,11,8,1

In [30]:
text_count.loc[text_count['messages']  > 10]['messages'].to_json('message-ranking.json')

In [31]:
px.bar(text_count.loc[text_count['messages'] > 10]['messages'], labels={'value' : '# of Messages', 'variable' : 'Message Type', 'sender' : 'Sender'})

In [32]:
text_count.loc[text_count['messages'] > 10][['texts', 'image', 'video']].to_json('text-image-ranking.json')

In [33]:
px.bar(text_count.loc[text_count['messages'] > 10][['texts', 'image', 'video']], labels={'value' : '# of Messages', 'variable' : 'Message Type', 'sender' : 'Sender'}, title="Messages Sent")

/Users/henrybrown/opt/anaconda3/envs/data_analysis/lib/python3.9/site-packages/plotly/express/_core.py:1979: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [34]:
df.head(40)

,texts,image,video,sender_number,reactions,reactions_received,sender
dates,,,,,,,
2025-06-03 08:03:02,Igor you legit do fuck all bro wake up,None,None,+16138588921,[Laughed by ryan.matson@icloud.com],1,Ben
2025-06-03 08:11:22,None,attachments/301/57215.jpeg,None,+16133559273,"[Laughed by +16138588921, Loved by +1416305426...",4,Igor
2025-06-03 08:44:58,throwback to the good ol days,attachments/301/57218.jpg,None,+14163054266,[Laughed by +16138588921],1,Austin
2025-06-03 09:07:33,None,attachments/301/57219.jpeg,None,+16133559273,[],0,Igor
2025-06-03 09:08:37,did you cop me any,None,None,+16134004076,[],0,Nick
2025-06-03 09:08:38,Thanks Jack,None,None,+16133559273,[],0,Igor
2025-06-03 09:09:25,I thought I ordered the little ones but it was...,None,None,+16133559273,[Laughed by itsjaxonmusic@gmail.com],1,Igor
2025-06-03 09:10:45,Good thing this wasn’t two months ago I would’...,None,None,+16133559273,[Laughed by +16134004076],1,Igor
2025-06-03 09:40:42,None,None,None,+16134004076,[],0,Nick
2025-06-03 10:31:31,None,attachments/301/57222.png,None,+15198782573,[],0,John
2025-06-03 13:52:01,Ben to igor,attachments/301/57226.jpg,None,+16133160960,"[Laughed by +16138588921, Laughed by +16134004...",4,Jack
2025-06-03 14:02:16,Igor is 6’3 and those are two different measur...,None,None,+16138588921,"[Laughed by +16133160960, Laughed by +16134004...",2,Ben
2025-06-03 14:36:00,None,None,None,+16133559273,"[Laughed by +16134004076, Laughed by +16138588...",4,Igor
2025-06-03 14:55:47,thibs:(,None,None,+14163054266,[],0,Austin
2025-06-03 14:58:03,Idk how i feel about it,None,None,ryan.matson@icloud.com,[],0,Ryan
2025-06-03 14:58:28,It’s not like the Knicks underperformed this year,None,None,ryan.matson@icloud.com,[],0,Ryan
2025-06-03 14:59:55,"they gonna hire a nonsense coach now, watch",None,None,+14163054266,[],0,Austin
2025-06-03 15:00:33,BREAKING: Doris Burke signs multi-million doll...,None,None,+14163054266,[Laughed by ryan.matson@icloud.com],1,Austin
2025-06-03 15:18:40,None,attachments/301/57227.jpeg,None,+16133559273,[Laughed by +14163054266],1,Igor
2025-06-03 15:22:44,None,attachments/301/57228.png,None,ryan.matson@icloud.com,"[Laughed by +14163054266, Laughed by +16134004...",4,Ryan
2025-06-03 15:22:45,None,None,None,ryan.matson@icloud.com,[],0,Ryan
2025-06-03 15:45:10,None,attachments/301/57229.jpeg,None,+16133559273,[],0,Igor
2025-06-03 15:45:15,Big bro it’s not kwanza,None,None,+16133559273,"[Laughed by +16138588921, Laughed by itsjaxonm...",2,Igor
2025-06-03 21:25:52,None,None,None,+16138588921,[],0,Ben
2025-06-03 21:25:53,Igor af,None,None,+16138588921,[],0,Ben
2025-06-03 21:35:33,Peegor,None,None,+15198782573,"[Laughed by +16138588921, Laughed by +16133559...",3,John
2025-06-03 22:34:48,Dare I say it?,None,None,+16138588921,[],0,Ben
2025-06-04 08:07:49,Good morning all,None,None,+16138588921,[],0,Ben
2025-06-04 09:07:27,Good ben all,None,None,+16048685587,[Loved by +16138588921],1,Michaela
2025-06-04 09:18:58,Wake up hole,None,None,+16133559273,[],0,Igor
2025-06-04 09:19:08,The biggest hole in the world,None,None,+16133559273,[Laughed by itsjaxonmusic@gmail.com],1,Igor
2025-06-04 09:19:16,We’re gonna be great,None,None,+16133559273,[Loved by +16048685587],1,Igor
2025-06-04 09:26:30,Who is 604,None,None,+16133559273,[],0,Igor
2025-06-04 09:27:56,Michaela Hole,None,None,+16048685587,[],0,Michaela
2025-06-04 09:29:07,Michaela let’s be best friends,None,None,+16133559273,[],0,Igor
2025-06-04 09:29:55,Trying to replace krys,None,None,ryan.matson@icloud.com,"[Laughed by +16138588921, Laughed by +16136202...",5,Ryan
2025-06-04 09:38:55,Igor never beating the Krys allegations,None,None,+16138588921,[],0,Ben
2025-06-04 09:45:13,Ben you live in such a poor neighbourhood bro ...,None,None,ryan.matson@icloud.com,"[Laughed by +16138588921, Laughed by +16133559...",2,Ryan
2025-06-04 09:58:01,"This is so fucked up, I wouldn’t even say this...",None,None,+16133559273,[],0,Igor
2025-06-04 10:00:11,Ben don’t listen to Ryan. You’re the greatest,None,None,+16133559273,[],0,Igor

In [35]:
list(df['texts'])

['Igor you legit do fuck all bro wake up',
 None,
 'throwback to the good ol days',
 None,
 'did you cop me any',
 'Thanks Jack',
 'I thought I ordered the little ones but it was actually full sized donuts. Our director is leaving so they tasked me with ordering treats',
 'Good thing this wasn’t two months ago I would’ve got 40 hat tricks',
 None,
 None,
 'Ben to igor',
 'Igor is 6’3 and those are two different measurements!',
 None,
 'thibs:(',
 'Idk how i feel about it',
 'It’s not like the Knicks underperformed this year',
 'they gonna hire a nonsense coach now, watch',
 'BREAKING: Doris Burke signs multi-million dollar deal to become new knicks head coach',
 None,
 None,
 None,
 None,
 'Big bro it’s not kwanza',
 None,
 'Igor af',
 'Peegor',
 'Dare I say it?',
 'Good morning all',
 'Good ben all',
 'Wake up hole',
 'The biggest hole in the world',
 'We’re gonna be great',
 'Who is 604',
 'Michaela Hole',
 'Michaela let’s be best friends',
 'Trying to replace krys',
 'Igor never beating the Krys allegations',
 'Ben you live in such a poor neighbourhood bro 😭 don’t get up you’re not gonna be the greatest',
 'This is so fucked up, I wouldn’t even say this to my worst enemy',
 'Ben don’t listen to Ryan. You’re the greatest',
 'Trying to frame something I’ve said as worse than your thinker comment',
 '99 times out of 100 I’m a nice guy. You just remember the one time',
 '“I build bridges all my life. Day after day I build bridges over rivers for my community, and they never call me “Bridge Builder Bob”. But I fuck a goat ONE TIME….”',
 None,
 'Cheronobyl ahh bike',
 None,
 'Igor is your family hutu or tutsi in Rwanda',
 'Bruh we’ve been though this before',
 '🧢',
 'Not me',
 'Bruh is inquiring to figure out if I was the victim or perpetrator',
 'LOOOOOOOL',
 'Bro you were only 9 when it happened. Obviously neither',
 'He already confirmed a while back he’s Hutu',
 None,
 'Holy linkage',
 'This was back in 2016',
 None,
 'Does anyone have any beginner friendly methods for escaping?',
 None,
 'Nah ur cooked gang',
 'shoe rotation of victims',
 'Jack take a high view point of 0.1',
 'Zoom out for me now',
 'Show us your Ish',
 'They tookAway my phone',
 'Bro texting from the Lenovo laptop',
 'Supple legs bro. Firm',
 'I… I thinking I see something. Oh m-my god.. it’s a thinkpad.',
 'For anyone not familiar with Jacks occasional doctor office post he’s doing this to see if he’s ready for the G-league',
 '(He’s not)',
 'But your legs are looking toned jack. might be time to join a run club',
 'Doctor Ruzindana keeps telling me that I have to keep giving him massages and maybe after 10 or 20 more I might be ready',
 None,
 'Bro lmaooo what',
 'My bad. He did tell me not to tell anyone',
 'He said the treatment might not be as effective if other people know',
 '2 years ago',
 'Riley only talks to the hole through reposts',
 None,
 'I am 19 years old and smoke cigarettes.',
 'Ever since the Toronto Maple Leaves incident',
 'Employed roley is a top 10 most boring person ever',
 'Unemployed riley is a top 3 most exciting person ever',
 'i have to agree with that',
 'it’s like night and day',
 'ri send a supportive message to the fam chat about gilbert',
 'Nah that’s fucking gross I’m not coming over anymore',
 'everyone be hatin',
 'Expected response to you getting a tarantula',
 'so lame',
 '“i’m never visiting. ugh.” seems like a dramatic reaction from my mum.',
 'add gilbert to the hole',
 'Me and Ryan dancing cuz we know Krys wouldn’t block us on IG',
 'Darcy erasure',
 'Paid actor',
 'ben u have the coolest shirts',
 'Thanks dude',
 'Now that im employed and not eating ground beef KD I’ve become a commoner',
 'Don’t worry guys I’ll be back in September',
 'Riley show us your meal upgrades',
 'Can you flex on Ben for me',
 None,
 'I had disaronno one time with ben and never again',
 'Second one is literally a frozen pizza',
 'Bro chill I can’t afford those at school',
 'i know ristorante thin crust when i see it',
 None,
 'LOOL',
 None,
 'Austin knows this is the good shit though',
 None,
 '😐',
 'Jon I know you sent that',
 'Burundians being unfairly targeted. Alternatively in glorious Rwanda 🇷🇼 there are no such issues.',
 'trump doing chad dirty',
 'He is afraid of being mogged',
 'Guys can everyone please send their outfit of the day',
 'jack ab to send a speedo',
 'Well now I’m not going to because it won’t be as funny',
 None,
 'where are u ordering food from',
 'igor sees a message like this as a bat signal to swoop in and gatekeep',
 'It was el Camino but it’s too expensive I’ll just order tacos from Ben’sBoingBoing’s',
 'Jack don’t tell him',
 'I’m really being pulled in two directions here nick',
 'second hand gatekeep begging is crazy',
 'He’s not even hungry',
 None,
 None,
 'buttered shaboing boing with da shell',
 'ben’s gonna see this and order it at east side mario’s',
 None,
 'ryans gonna see it and be like yooooo delicacy in jasper',
 'Skip the dishes open on the laptop is peak fattery',
 None,
 'Legendary pic',
 'Jack darcy and I playing skip the dishes multiplayer in 2019',
 'Holy fuck who won?',
 'The driver. They tip well',
 'John',
 'u dont post lattes anymore:(',
 None,
 'how much to ship a crème brûlée latte',
 None,
 'Check uber eats prices',
 'if i order a drink on uber eats are u the one making it',
 'Bens BoingBoings is probably the same price range as Canadas Wonderland hotdogs',
 '$13 one Boing, second Boing is extra',
 'how much for the Sha before the Boings',
 '$6',
 'condiments not included',
 'brah',
 'steep asf',
 'how much for chup',
 '“come on down to Bens ShaBoingBoing, where everything is chopped & cooked”',
 'Igor u wanna hit crazy horse',
 None,
 'without me ????',
 'coincidence, I’m going on the 14th',
 'Coincidence that you’re also going to prom this year too?',
 None,
 'You’re fucked looool',
 'I’m going because it’s the afterparty on',
 'Okay and why does that make you get to go to Prom',
 'Brah I had no idea it’s prom, every year PBR makes it the official afterparty',
 'It’s come to my attention you’re well informed which date prom falls on',
 'This isn’t about me.',
 'It is now given the revelation',
 None,
 'Ben Self Implicator Maycock',
 'bro and last name Maycock',
 'Couldn’t write a better script',
 '☹️',
 'last name shaming is crazy',
 'Who’s your prom date ?',
 'And did you prom-pose ?',
 'and was it on school property ?',
 '#HighschoolHuzz #Ben',
 None,
 'Ben’s prom date is high-key girl ryan',
 'Slide me ya snap tho',
 'Nick af',
 'Stray af',
 'Ben’s crib probably',
 'Yesssssss',
 None,
 'ben when did you join the mob',
 'Can we get the ben stache back',
 None,
 'LOL',
 None,
 'yes',
 'I have 0.00000046 CAD in dogecoin in my wealth Simple crypto wallet because there was an error withdrawing it like 6 years ago',
 'Dude same',
 'and it’s stuck',
 'So yes I would let him if he could fix that',
 'He will',
 'Give him (me) your passwords',
 None,
 'Diamond hands',
 None,
 'igor we gotta talk ab haliburton',
 'Haliban',
 'I’m not watching game 1',
 'Newsflash, game 1 is over',
 'Well you can’t, it’s over',
 'Mr Peegor',
 'ok good',
 'Igor was busy studying Ish film',
 'Fuck that guy',
 'Haliburton not Ish',
 'Actually nah fuck Ish too',
 'My fever dream would be them playing on the same team',
 None,
 'Bro thinks hes Krys',
 'Ben ur literally obsessed with me',
 'And u need to STOPPP because it’s pissing me off',
 'No offence but you are not someone who should be judging who im obsessed with',
 None,
 'Rigging the system',
 'Igor watching pheonix mercury vs golden state valkyries',
 'Brah lol',
 'With he meat out',
 None,
 'What team hailey vanlith on',
 'that’s the team I’ll be watching',
 'Igor is an inverse snowbunny',
 'nah',
 'Yea, hes a nonce',
 'hailey van lith looks like a 12 yr old',
 'a very hard exaggeration',
 'Igor send a selfie rn',
 None,
 'Bruh sitting on it',
 'Zac efron ah hooper',
 'posing like it’s srb junior girls team photo',
 'LOOL',
 'literally 11',
 None,
 None,
 'John NFT lol',
 'I have him as John',
 None,
 'For Darcy',
 None,
 'Deadass Nick after coming back from Orleans',
 None,
 'New NFT, tap in',
 None,
 None,
 'John sending his own joke to another chat',
 'I specifically didn’t send that screenshot in here cuz I thought it was a bit offside!',
 'Igor, do you still want me to always send your Krys’ posts since you can’t see them',
 'Honestly leave krys alone',
 'Fuck wrong group',
 'LMAOOOOOO',
 'I’m crying bruh',
 'Ben ngl you’ve been acting like such a loser lately',
 'No offence taken, I’ve been trying to act like one',
 'Literally unbeatable comeback',
 None,
 'I’m no longer sober BTW',
 'Can you confirm the second part?',
 'Big Teautiful Women?',
 'Made it to 100 days and that first beer back hit like crack',
 'Can you not be a cheap OC transpo riding fuck for once',
 'I’ve been carpooling with someone who has a car don’t worry',
 'CEO of busbuddy and rocketbus',
 'Jack can you ask Keith if I can borrow his car tn',
 'He said yes.',
 'And then he said “Just kidding you dumbass who is ben”',
 'Whenever I picture Jacks dad I picture Brady Tkachuks dad who is also named Keith',
 'LOOL',
 'Lowkey. He doesn’t look unlike Keith Tkachuk',
 'Ben meets a girl. They hit it off (he thinks) … he gets her number and it’s',
 'Nah he said “No thoughts. I’m a few drinks into the evening”',
 'Here is Keith Tkachuk. I found him in Florida at a sens game a few years ago, he was destroying a donut. He also scored 500 NHL goals',
 'lard ass',
 'Ish-riding someone’s dad',
 'LOOOL',
 'Ben is the type of guy to clap before the bus driver lets him off',
 'LOOOOL',
 'My dad is not on the same Tubb level as Keith Tkahuk. Respect to Keiths',
 'You know it’s a',
 'Bro I have a zonnic in my mouth right now and everything is so fucking funby',
 'Well known hallucinogenic, zonnic',
 'zonnics are like mushrooms for ben',
 'Ben legit used to rip a Dr Pepper and go make out with girls at le pub so this trajectory is entirely non surprising',
 'If I stop responding it’s cuz I’m throwing up lol',
 'holy fuck i’m crying',
 'Igor we celebrating?',
 'Ben and Igoe have such a big/little brother dynamic',
 'Igoe ❤️\u200d🩹',
 'Ben there’s a private event',
 'Don’t act like either of us are getting in without Jack and Darcy',
 'Igoe 🥀😞',
 'Jack in the box, Cracker Jack, Jack black, Black Jack',
 'Idc',
 'Ish in 5',
 'Igoe and Bing are so funny. I’m lowkey chuckling just reading some of the shit',
 None,
 'You wouldn’t last a day in Sault Ste Marie bro',
 None,
 'Jack gettin his ID checked by the bouncer while not trying to look inebriated af',
 'Do you have Italians in the soo ben',
 'Yup, all the got is Aboriginals, Italians and some recent Indians',
 'Hidden tier list',
 'also it’s indigenous now not aboriginal',
 'Classic Ontaritalian to have family in the soo',
 'Raccccccccciiii',
 'Who has the pic of me infront of the train',
 'That’s in the soo',
 None,
 'Yes',
 'My early stomping grounds',
 'Asking for a pic and then just responding “yes” to it is insane',
 'Like you didn’t need it you just needed to confirm absolutely nothing',
 'Igor as fuck',
 'Fucking love that meme so much',
 None,
 'Ignore the hockey graphic',
 'I cannot wait to see this insane new body',
 'Ben you’re very lustful lately',
 'And that’s coming from an elite freakazoid',
 'That’s cuz I’ve been depressed for about 8 months Peegor',
 'What goes down must come up bruh',
 'Freaky ahh Sir Isaac Newton',
 'Bruh meeting Lebron saying shit like “Im a fan of your body”',
 None,
 None,
 'Bruh is named V(ISH-WADE)V',
 None,
 'The zone of Pinterest',
 None,
 'Austin',
 'igor',
 None,
 'Genuinely one of the hardest watches of my life',
 'what do you get when you cross the Atlantic with the Titanic',
 'A shipwreck',
 'no, halfway',
 'Fantastic',
 'do ppl still make walmartian videosi think they should',
 'guys i bought a dvd playerand a bunch of dvds',
 'You’re gonna be just like Josh maycock',
 'Get the collage ready',
 None,
 'What the fuck is le spenis',
 'The opposite of la gina',
 'Ok fair enough',
 None,
 None,
 None,
 'we let the smog talk #IYKYK',
 'Lmfaooo',
 'Smoggish in my bog',
 'Lesson in there for you ben🙏⬆️',
 'Who is this',
 None,
 'Darcy can’t believe you got claimed by a member of the Gayborhood',
 'and a Mario Judah lookalike finessed your cigarette. Rough night',
 'And Nick got hit on by a bartender',
 'And I got this voicemail',
 None,
 'For context this wasn’t all me, I passed the phone around😂',
 '🧢',
 'Who’s lines are who ?',
 'darcy and i hit an elgin st diner 2 man pr',
 None,
 'Me cutting Ryan’s hair',
 'Yeah lemme get 93 cents on pump 5',
 'I’m crying',
 'No wonder you couldn’t link up',
 'LOOL',
 'LOOOL',
 'Darcy was sending very mean voicemails meanwhile Bens tryna Fred flinstone his way to Elgin',
 'Ben you just had to be there so many girls were crowded around us (capacity)',
 'Ben drop the audio',
 'Let’s see who said what',
 'Do not drop the audio',
 None,
 'It will only ruin Darcy’s image more',
 'Ben do not leak the audio transcript I repeat do NOT',
 'Let’s see who said what',
 'I’ll send it after',
 'nah you’re good bro',
 'benmobile',
 'LOL',
 None,
 'LOOL',
 None,
 None,
 None,
 'Ben',
 'Fine that is me',
 None,
 'just watched my tarantula annihilate his dinner',
 'Say word he ate riley 🥀😞',
 'but did u take a video',
 'nah lighting sucked bc no sunlight and i didnt wanna put a light on him',
 'Legit worst purchase by a Burke ever',
 'nahi’ll sick him on you for saying that',
 None,
 'What do wild tarantulas do during the day',
 'chill',
 'They stroke their pingus Ryan',
 'Bro why me',
 'Because you’re the nature guy',
 'I’d fucking shoot it with a 12 gauge infront of you sorry',
 'How u gonna shoot it from inside its belly gang 😂🥀',
 'he would bite u before thathe’s venomous too',
 None,
 'Gilbert ain’t bulletproof',
 'I’m manifesting Mack walking in on her spider wrapping riley up in a big ass web',
 'i’ll train him to do that',
 'Who up striking their igor with a clenched fist',
 'how i be striking my igor',
 None,
 'what kinda trout is thatbrook? so pretty',
 'Plus Ryan you work at Park Omega so it’s only right',
 'ryan respectfully i gave you a heart react to that already in a different GC',
 'All good boss carry on',
 'Or park Canada whatever',
 None,
 '$5 if you want another',
 'David Thompson. Yes Liam Courtney Alex Sierra and I',
 None,
 'Yo is Ben Jewish ????',
 'yes',
 'Bruh',
 'Nice pal',
 'Nooooooo',
 None,
 'Ben on Jew slime watch for igor',
 'LOL',
 'it all makes sense now',
 'Brookie yea',
 'Yews',
 None,
 'So pretty',
 'The females are less colourful but similar vibe',
 'bruh holy who let the dogs out',
 'i love salmonidsprobs my fav fish group',
 'throw them on the grillaz',
 'Did you stub your right second big toe',
 'I finished my run last weekend and it’s just looked like this since',
 'Nicks mad cuz I went for a swim in the jorts',
 'Bro looool',
 'Bro dressed like a castaway',
 'Wet jorts, all possessions washed up on shore',
 'infinitely worse than the vans in the water',
 None,
 'Raw dennnnyyy',
 'Legit nothing wrong with a jwim',
 'how has your toenail not fallen off',
 'I have no idea dude',
 'I can’t say anything I rip the Juvet, big Jean advocate',
 'i thought you got rid of the juvet',
 'Found it',
 'Also I didn’t get rid of it my opps (mom) did',
 'Bro there’s something liberating about wearing jean shorts in the backcountry and just not taking them off for 3 days',
 'i lowkey like hiking in some old baggy jeansin winter at leastway more durable and dry faster and keep ya warm if ya throw long johns underneath',
 'Yea I actually felt free, I have a lot of “hiking pants” but none of them feel as good as rocking some baggy jorts',
 None,
 'LOOOL',
 'If you wanna feel clean you hop in the water with em',
 'Besus',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Get off my dick',
 None,
 None,
 None,
 None,
 None,
 None,
 'Who up collecting Ryan’s',
 'John mentioned 🔥💯',
 'i’m still stuck on jwim',
 'See you guys in 1-2 weeks',
 'Riley ngl you been kindve a winner lately',
 'just locked in, securing bag and collecting Ryan’s',
 'I popped a 15 milly zynarama and had to fire a couple out before smacking pillow',
 'You popped a what',
 'English man',
 'it’s 19 yr old comm bro speak',
 'we gotta recreate the boyz trip ryan and ribut west coast edition',
 '15mg Zyn ™',
 'I’m already going brah',
 'I’m 20',
 'i swear u just turned 19',
 'I swear you just turned 24',
 'i did',
 'Ok 👍',
 'you just made me second guess myselfyes you are 19 until nov 2005 baby',
 'Yes',
 'good night hole',
 "Yo, we hit the town, lights glowin’ all around,Igor dripped out… 'til slime hit the ground.Nick chillin’ back, Darcy flexin' with the flair,But Igor got curved, man — life just ain't fair.",
 'but can we hear you rap/sing it',
 None,
 'Igor posts and deletes MYSTERIOUS ranking',
 'There’s a lesson in there for you Ben',
 'Be careful Jack you are one project away from being added',
 '#Whitelisted',
 'Why am I only finding out about this website through ChatGPT',
 None,
 'Joining the email list so I have early access to epic content',
 'I am notEmailing yo ahh 🖕',
 'Come on bro',
 'I had to make this shit to apply for grants',
 'I legit put in ChatGPT “do you know who Jack Moss is”',
 'There’s a shop with no items to buy',
 'You’ve just been banned from purchasing the',
 'Ryan they sold out',
 'Sold out of',
 'Dw about it',
 'You just had to be there',
 'You guys hit another private event this past weekend didn’t you…',
 'You’re just not you when you’re going to private events',
 'Nah (yes)',
 'but you had to be there',
 'I need join the Illuminati. Gatekeeping is not enough',
 'Igor, we should join a Masonic lodge',
 'Check the vibe',
 None,
 'Igor ngl you’ve been acting like such a loser lately',
 'My website notEven that bad. Hatress',
 None,
 'Austin be like iggy can I come over and leave strands of hair in your bed sheets',
 'Nah gang 🥀😂',
 'Gang ay',
 'Ben',
 'would be the first kinky hair your bedsheets ever seen',
 'What U want peegor',
 'Peegor',
 'What’s next neegor ??',
 'LOL',
 'Say it Ben I know ur itching',
 'I know my jokes hit like a mf when henry is giggling',
 'so racism is funny now?',
 'Omg bruh get this dude outta here',
 'Austin you’re literally jaden smith',
 'Everyone bet panthers money line',
 'Sens in 7 tbh',
 'YOOOOOOOOOOO',
 'Completely forgot Nate was added to hole',
 '613-261 is firing me up rn',
 'I keep wondering why I have 100 text messages',
 'We’re digging the hole',
 'Melanie come to the pump',
 'invite only event',
 'Austin',
 'i love the pump',
 'Funny that Melanie will reply in here but not to my messages!',
 'Ben have you ever considered that you might actually be a loser',
 None,
 "igor you're literally obsessed with me",
 'Igor is dick riding with no license',
 'Respectfully Mr. 93 cents on pump 5 … stfu',
 None,
 'Ben in the new fast & furious movie but it’s just him calling vin diesels like “yo my tanks on E can’t come to the mission”',
 'LOL',
 'End credits',
 'its just paul walker on the high driving alone',
 'Austin and I',
 'LOL',
 'Guys please no jokes about me and gas, it will make Nick and Ryan laugh too much',
 None,
 'Nick at the pump trying to get darcy and I to run a play.',
 'LOOOL',
 '8 fumbles, 0 touchdowns, 0 yards',
 'i unfortunately did not foresee the two man attempt becoming a 5 on 2',
 'next time i’ll anticipate it and i’ll have mike and nate play more off ball defence',
 'Nick what’s your boys name that was with us',
 'mike and he’s in the hole',
 'Mike if you’re reading this you let us down',
 None,
 'LOL',
 'No huzz',
 'I secured the one man pre pump entrance',
 'Sorry fellas',
 'bruh igor u must’ve had a good sleep last night you’re extra funny',
 "bro goon'd all night for this",
 'I was in line bag secured yall need to get your funny up',
 '2 man thru the window was crazy work',
 'Ngl nate you had a homecourt advantage',
 'Don’t worry igor we have prom night at the crazy horse this weekend',

In [36]:
df['texts'].fillna('')

dates
2025-06-03 08:03:02               Igor you legit do fuck all bro wake up
2025-06-03 08:11:22
2025-06-03 08:44:58                        throwback to the good ol days
2025-06-03 09:07:33
2025-06-03 09:08:37                                   did you cop me any
                                             ...
2025-06-30 22:45:50                                          Goated show
2025-06-30 22:51:31                                                  Lol
2025-06-30 22:52:02                         The script writes itself Ben
2025-06-30 23:14:02                                                  Ben
2025-06-30 23:14:29    If it’s well received you can live with them a...
Name: texts, Length: 2750, dtype: object

In [37]:
df['word_count'] = df['texts'].fillna('').apply(lambda x : len(x.split(' ')))

/var/folders/zm/kglhp53x58752bpgh6114_f40000gn/T/ipykernel_4337/112821834.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [38]:
word_count = df.groupby('sender').sum().sort_values(by='word_count', ascending=False)

In [39]:
text_count['word_count'] = word_count.word_count

In [40]:
text_count.loc[text_count.word_count >= 50]["word_count"].sort_values(ascending=False).to_json("word-count.json")

In [41]:
fig = go.Figure(data=[go.Bar(
            x=word_count.index, y=word_count['word_count'],
            text=word_count['word_count'],
            textposition='auto',
        )])

fig.update_layout(
    title="Word Count",
    xaxis_title="Sender",
    yaxis_title="Words",
)

fig.show()

In [42]:
text_count.loc[text_count['hahas_sent'] > 10]['hahas_sent'].sort_values(ascending=False).to_json("hahas-sent.json")

In [43]:
fig = go.Figure(data=[go.Bar(
            x=text_count['hahas_sent'].sort_values(ascending=False).index, y=text_count['hahas_sent'].sort_values(ascending=False),
            text=text_count['hahas_sent'].sort_values(ascending=False),
            textposition='auto',
        )])

fig.update_layout(
    title="Hahas Sent",
    xaxis_title="Sender",
    yaxis_title="Haha Count",
)

fig.show()

In [44]:
(text_count.loc[text_count['messages'] > 10]['reactions_received'] / text_count.loc[text_count['messages'] > 10]['messages']).sort_values(ascending=False).to_json("ratio.json")

In [45]:
(text_count.loc[text_count['messages'] > 10]['reactions_received'] / text_count.loc[text_count['messages'] > 10]['messages']).sort_values(ascending=False)

sender
Greg            1.055556
Henry           1.000000
Ryan            0.959569
John            0.900662
Jack            0.730088
Austin          0.684211
Igor            0.632514
Ben             0.581818
Darcy           0.580952
+16132612783    0.510040
Nick            0.371212
Mack            0.364583
Riley           0.343750
dtype: float64

In [46]:
most_reacted_text = pd.Series()
images_and_videos = []

for sender in list(df.sender.unique()):
    if df.loc[df.sender == sender].reactions_received.max() > 1:
        most_reacted_text[sender] = df.loc[
            (df.sender == sender) & 
            (df.reactions_received == df.loc[df['sender'] == sender].reactions_received.max())][['texts', 'image', 'video', 'reactions_received']
        ].to_dict(orient="records")
        
        images_and_videos += (list(df.loc[(df.sender == sender) & (df.reactions_received == df.loc[df['sender'] == sender].reactions_received.max())]['image'].values))
        images_and_videos += (list(df.loc[(df.sender == sender) & (df.reactions_received == df.loc[df['sender'] == sender].reactions_received.max())]['video'].values))
    else:
        most_reacted_text[sender] = None

In [47]:
images_and_videos = [entry for entry in images_and_videos if entry]

In [48]:
keep_files = set(os.path.abspath(f) for f in images_and_videos)

In [49]:
all_files = glob.glob("attachments/**/*", recursive=True)

for file in all_files:
    if os.path.isfile(file) and os.path.abspath(file) not in keep_files:
        os.remove(file)
        print(f"Deleted: {file}")

print("Cleanup complete.")

Deleted: attachments/301/58359.jpg
Deleted: attachments/301/57465.jpeg
Deleted: attachments/301/58456.jpeg
Deleted: attachments/301/57417.heic
Deleted: attachments/301/58006.jpeg
Deleted: attachments/301/57941.mov
Deleted: attachments/301/57824.jpeg
Deleted: attachments/301/57606.gif
Deleted: attachments/301/58007.jpg
Deleted: attachments/301/57636.caf
Deleted: attachments/301/57648.jpeg
Deleted: attachments/301/57650.PNG
Deleted: attachments/301/57334.png
Deleted: attachments/301/58207.jpeg
Deleted: attachments/301/57484.png
Deleted: attachments/301/58330.heic
Deleted: attachments/301/57405.gif
Deleted: attachments/301/57664.jpeg
Deleted: attachments/301/57679.jpg
Deleted: attachments/301/58315.jpeg
Deleted: attachments/301/57637.caf
Deleted: attachments/301/57263.jpeg
Deleted: attachments/301/57330.jpeg
Deleted: attachments/301/58180.JPEG
Deleted: attachments/301/57737.jpeg
Deleted: attachments/301/58289.jpeg
Deleted: attachments/301/57531.JPG
Deleted: attachments/301/57594.jpeg
Deleted: attachments/301/58374.jpeg
Deleted: attachments/301/57701.jpeg
Deleted: attachments/301/58227.jpeg
Deleted: attachments/301/57994.jpeg
Deleted: attachments/301/58212.png
Deleted: attachments/301/58362.jpeg
Deleted: attachments/301/57613.jpeg
Deleted: attachments/301/58437.jpeg
Deleted: attachments/301/58067.jpeg
Deleted: attachments/301/57541.jpeg
Deleted: attachments/301/58213.jpg
Deleted: attachments/301/57404.jpeg
Deleted: attachments/301/57608.caf
Deleted: attachments/301/57280.jpeg
Deleted: attachments/301/58084.MOV
Deleted: attachments/301/57421.heic
Deleted: attachments/301/58460.jpeg
Deleted: attachments/301/57604.gif
Deleted: attachments/301/58373.png
Deleted: attachments/301/57599.mov
Deleted: attachments/301/57281.jpg
Deleted: attachments/301/57530.JPG
Deleted: attachments/301/57518.jpg
Deleted: attachments/301/58071.jpeg
Deleted: attachments/301/57384.jpeg
Deleted: attachments/301/57412.jpeg
Deleted: attachments/301/57940.jpeg
Deleted: attachments/301/58070.jpeg
Deleted: attachments/301/58363.png
Deleted: attachments/301/58477.jpeg
Deleted: attachments/301/58015.JPG
Deleted: attachments/301/57452.jpeg
Deleted: attachments/301/57468.jpg
Deleted: attachments/301/58217.png
Deleted: attachments/301/57420.heic
Deleted: attachments/301/57540.jpeg
Deleted: attachments/301/57333.png
Deleted: attachments/301/58014.png
Deleted: attachments/301/58056.gif
Deleted: attachments/301/57307.jpeg
Deleted: attachments/301/58264.caf
Deleted: attachments/301/57429.jpeg
Deleted: attachments/301/57995.jpeg
Deleted: attachments/301/57645.jpeg
Deleted: attachments/301/57915.m4a
Deleted: attachments/301/57469.jpg
Deleted: attachments/301/57215.jpeg
Deleted: attachments/301/57350.jpeg
Deleted: attachments/301/57816.caf
Deleted: attachments/301/57595.jpeg
Deleted: attachments/301/58375.jpeg
Deleted: attachments/301/57247.jpg
Deleted: attachments/301/57346.jpeg
Deleted: attachments/301/58288.jpeg
Deleted: attachments/301/58446.mov
Deleted: attachments/301/57311.jpeg
Deleted: attachments/301/58360.jpg
Deleted: attachments/301/57673.jpeg
Deleted: attachments/301/57549.gif
Deleted: attachments/301/57537.jpg
Deleted: attachments/301/57286.jpg
Deleted: attachments/301/58482.jpeg
Deleted: attachments/301/57262.jpeg
Deleted: attachments/301/57632.jpeg
Deleted: attachments/301/58314.jpeg
Deleted: attachments/301/58214.PNG
Deleted: attachments/301/58331.heic
Deleted: attachments/301/57665.jpeg
Deleted: attachments/301/58206.jpeg
Deleted: attachments/301/57472.jpeg
Deleted: attachments/301/58055.gif
Deleted: attachments/301/57640.JPG
Deleted: attachments/301/57219.jpeg
Deleted: attachments/301/57649.jpeg
Deleted: attachments/301/57668.png
Deleted: attachments/301/58215.PNG
Deleted: attachments/301/57456.JPG
Deleted: attachments/301/57825.jpeg
Deleted: attachments/301/58379.jpeg
Deleted: attachments/301/57576.jpeg
Deleted: attachments/301/57258.JPEG
Deleted: attachments/301/58457.jpeg
Deleted: attachments/301/57416.heic
Deleted: attachments/301/57278.png
Deleted: attachments/301/57464.jpeg
Deleted: attachments/301/57548.gif
Deleted: attachments/301/58188.png
Deleted: attachments/301/57587.caf
Deleted: attachments/301/57287.PNG
Deleted: attachments/301/58361.jpg
Deleted: attachments/301/57603.jpeg
Deleted: attachments/301/58448.jpg
Deleted: attachments/301/58312.JPG
Deleted: attachments/301/57592.PNG
Deleted: attachments/301/58378.mov
Deleted: attachments/301/57790.JPG
Deleted: attachments/301/58325.jpeg
Deleted: attachments/301/58372.jpeg
Deleted: attachments/301/57586.jpg
Deleted: attachments/301/57343.JPG
Deleted: attachments/301/58221.jpeg
Deleted: attachments/301/57992.jpeg
Deleted: attachments/301/57828.jpg
Deleted: attachments/301/58299.jpeg
Deleted: attachments/301/57815.jpg
Deleted: attachments/301/57547.jpeg
Deleted: attachments/301/57626.png
Deleted: attachments/301/58489.jpeg
Deleted: attachments/301/58267.png
Deleted: attachments/301/57427.heic
Deleted: attachments/301/57269.jpeg
Deleted: attachments/301/57829.PNG
Deleted: attachments/301/58470.jpeg
Deleted: attachments/301/57544.JPG
Deleted: attachments/301/58309.jpeg
Deleted: attachments/301/57222.png
Deleted: attachments/301/57678.jpeg
Deleted: attachments/301/57752.JPG
Deleted: attachments/301/57930.jpeg
Deleted: attachments/301/58329.jpeg
Deleted: attachments/301/57988.jpg
Deleted: attachments/301/58463.jpg
Deleted: attachments/301/58450.jpeg
Deleted: attachments/301/57554.heic
Deleted: attachments/301/58488.png
Deleted: attachments/301/57546.JPG
Deleted: attachments/301/57822.jpeg
Deleted: attachments/301/57658.jpeg
Deleted: attachments/301/57588.jpeg
Deleted: attachments/301/57630.png
Deleted: attachments/301/57666.mov
Deleted: attachments/301/58295.jpeg
Deleted: attachments/301/58016.jpeg
Deleted: attachments/301/57818.jpeg
Deleted: attachments/301/57341.PNG
Deleted: attachments/301/57667.mov
Deleted: attachments/301/58313.jpeg
Deleted: attachments/301/58258.PNG
Deleted: attachments/301/57355.jpg
Deleted: attachments/301/57635.jpeg
Deleted: attachments/301/58305.jpeg
Deleted: attachments/301/57623.jpeg
Deleted: attachments/301/58186.jpeg
Deleted: attachments/301/58476.jpg
Deleted: attachments/301/57674.jpeg
Deleted: attachments/301/57360.jpeg
Deleted: attachments/301/58328.JPG
Deleted: attachments/301/57675.jpeg
Deleted: attachments/301/57972.jpg
Deleted: attachments/301/57914.caf
Deleted: attachments/301/57622.jpeg
Deleted: attachments/301/58366.caf
Deleted: attachments/301/58241.jpeg
Deleted: attachments/301/57475.mov
Deleted: attachments/301/57379.jpg
Deleted: attachments/301/57634.jpeg
Deleted: attachments/301/57458.jpeg
Deleted: attachments/301/58017.jpeg
Deleted: attachments/301/58447.jpeg
Deleted: attachments/301/57344.PNG
Deleted: attachments/301/57474.jpeg
Deleted: attachments/301/58021.mov
Deleted: attachments/301/57566.jpeg
Deleted: attachments/301/58063.jpg
Deleted: attachments/301/57659.jpeg
Deleted: attachments/301/58367.caf
Deleted: attachments/301/57266.mov
Deleted: attachments/301/57218.jpg
Deleted: attachments/301/57989.jpeg
Deleted: attachments/301/57462.jpeg
Deleted: attachments/301/57931.jpeg
Deleted: attachments/301/57581.PNG
Deleted: attachments/301/58467.JPG
Deleted: attachments/301/57382.m4a
Deleted: attachments/301/57229.jpeg
Deleted: attachments/301/58308.jpeg
Deleted: attachments/301/57226.jpg
Deleted: attachments/301/57597.jpg
Deleted: attachments/301/57583.jpg
Deleted: attachments/301/58471.jpeg
Deleted: attachments/301/58061.JPG
Deleted: attachments/301/58263.png
Deleted: attachments/301/57426.heic
Deleted: attachments/301/57268.jpeg
Deleted: attachments/301/58442.heic
Deleted: attachments/301/58439.heic
Deleted: attachments/301/57347.png
Deleted: attachments/301/57309.caf
Deleted: attachments/301/57614.jpeg
Deleted: attachments/301/58220.jpeg
Deleted: attachments/301/57993.jpeg
Deleted: attachments/301/57643.jpeg
Deleted: attachments/301/58060.jpg
Deleted: attachments/301/57627.heic
Deleted: attachments/301/57593.jpeg
Deleted: attachments/301/57582.JPG
Deleted: attachments/301/57762.heic
Deleted: attachments/301/57517.MOV
Deleted: attachments/301/57340.jpeg
Deleted: attachments/301/57710.jpeg
Deleted: attachments/301/57945.jpeg
Deleted: attachments/301/57532.gif
Deleted: attachments/301/57553.jpeg
Deleted: attachments/301/57264.caf
Deleted: attachments/301/58075.jpeg
Deleted: attachments/301/57570.png
Deleted: attachments/301/58281.m4a
Deleted: attachments/301/58333.png
Deleted: attachments/301/57457.jpeg
Deleted: attachments/301/57425.heic
Deleted: attachments/301/57284.jpeg
Deleted: attachments/301/57644.mov
Deleted: attachments/301/58441.heic
Deleted: attachments/301/57545.jpeg
Deleted: attachments/301/57485.gif
Deleted: attachments/301/57453.gif
Deleted: attachments/301/57607.JPG
Deleted: attachments/301/57990.JPEG
Deleted: attachments/301/58093.JPG
Deleted: attachments/301/57569.jpeg
Deleted: attachments/301/58223.jpeg
Deleted: attachments/301/57761.heic
Deleted: attachments/301/57331.heic
Deleted: attachments/301/57590.jpeg
Deleted: attachments/301/57968.JPG
Deleted: attachments/301/57314.jpeg
Deleted: attachments/301/57533.GIF
Deleted: attachments/301/57676.jpeg
Deleted: attachments/301/57271.jpeg
Deleted: attachments/301/58184.jpeg
Deleted: attachments/301/57567.JPG
Deleted: attachments/301/58424.caf
Deleted: attachments/301/57598.JPG
Deleted: attachments/301/57765.PNG
Deleted: attachments/301/58307.jpeg
Deleted: attachments/301/58468.jpeg
Deleted: attachments/301/57267.jpeg
Deleted: attachments/301/58226.heic
Deleted: attachments/301/58311.jpeg
Deleted: attachments/301/57605.JPG
Deleted: attachments/301/58203.jpeg
Deleted: attachments/301/58293.jpg
Deleted: attachments/301/58444.jpeg
Deleted: attachments/301/57477.jpeg
Deleted: attachments/301/57709.jpeg
Deleted: attachments/301/58413.jpeg
Deleted: attachments/301/58292.png
Deleted: attachments/301/57820.jpeg
Deleted: attachments/301/57295.gif
Deleted: attachments/301/57228.png
Deleted: attachments/301/57932.jpeg
Deleted: attachments/301/57525.jpeg
Deleted: attachments/301/58280.jpeg
Deleted: attachments/301/57774.jpg
Deleted: attachments/301/57460.jpeg
Deleted: attachments/301/57285.gif
Deleted: attachments/301/57821.jpeg
Deleted: attachments/301/58238.jpeg
Deleted: attachments/301/57520.MOV
Deleted: attachments/301/57964.jpeg
Deleted: attachments/301/58335.png
Deleted: attachments/301/58347.caf
Deleted: attachments/301/57748.PNG
Deleted: attachments/301/57589.jpg
Deleted: attachments/301/58057.JPG
Deleted: attachments/301/57600.png
Deleted: attachments/301/58094.jpg
Deleted: attachments/301/58255.jpg
Deleted: attachments/301/57642.mov
Deleted: attachments/301/57628.jpg
Deleted: attachments/301/57476.jpeg
Deleted: attachments/301/58296.jpg
Deleted: attachments/301/58445.jpeg
Deleted: attachments/301/57371.PNG
Deleted: attachments/301/58283.jpg
Deleted: attachments/301/58081.jpeg
Deleted: attachments/301/58310.jpeg
Deleted: attachments/301/58469.jpeg
Deleted: attachments/301/57428.heic
Deleted: attachments/301/57323.jpeg
Deleted: attachments/301/57638.m4a
Deleted: attachments/301/57775.PNG
Deleted: attachments/301/58306.jpeg
Deleted: attachments/301/58185.jpeg
Deleted: attachments/301/57270.jpeg
Deleted: attachments/301/57577.jpg
Deleted: attachments/301/57563.jpg
Deleted: attachments/301/58481.AVIF
Deleted: attachments/301/57227.jpeg
Deleted: attachments/301/57677.jpeg
Deleted: attachments/301/58334.jpg
Deleted: attachments/301/58452.jpg
Deleted: attachments/301/58092.m4a
Deleted: attachments/301/57987.jpg
Deleted: attachments/301/57342.jpeg
Deleted: attachments/301/58058.jpeg
Deleted: attachments/301/57657.JPEG
Deleted: attachments/301/58336.png
Deleted: attachments/301/57830.PNG
Deleted: attachments/301/57991.jpeg
Deleted: attachments/301/58083.jpg
Deleted: attachments/301/58222.jpeg
Deleted: attachments/301/58256.JPG
Deleted: attachments/301/58449.jpeg
Deleted: attachments/301/57408.heic
Deleted: attachments/301/57616.jpeg
Deleted: attachments/301/57641.mov
Deleted: attachments/301/58068.PNG
Deleted: attachments/301/57378.JPEG
Deleted: attachments/301/58294.jpg
Deleted: attachments/301/57536.heic
Deleted: attachments/301/58339.heic
Deleted: attachments/301/58440.heic
Deleted: attachments/301/57424.heic
Deleted: attachments/301/58082.JPG
Deleted: attachments/301/58257.PNG
Deleted: attachments/301/58259.jpeg
Deleted: attachments/301/58023.jpeg
Deleted: attachments/301/57432.heic
Deleted: attachments/301/57505.jpeg
Deleted: attachments/301/57274.caf
Deleted: attachments/301/58074.jpeg
Deleted: attachments/301/57560.PNG
Deleted: attachments/301/58218.jpeg
Deleted: attachments/301/57944.jpeg
Deleted: attachments/301/57552.jpeg
Deleted: attachments/301/58356.jpeg
Deleted: attachments/301/58478.jpeg
Deleted: attachments/301/57551.mov
Deleted: attachments/301/57918.jpeg
Deleted: attachments/301/57631.jpeg
Deleted: attachments/301/57467.jpg
Deleted: attachments/301/57324.jpeg
Deleted: attachments/301/57315.jpg
Deleted: attachments/301/57473.JPG
Deleted: attachments/301/58317.jpeg
Deleted: attachments/301/57478.heic
Deleted: attachments/301/58205.jpeg
Deleted: attachments/301/57300.PNG
Deleted: attachments/301/57308.jpeg
Deleted: attachments/301/58291.jpeg
Deleted: attachments/301/57922.jpeg
Deleted: attachments/301/58219.PNG
Deleted: attachments/301/58045.jpeg
Deleted: attachments/301/58229.jpeg
Deleted: attachments/301/57975.jpeg
Deleted: attachments/301/57349.jpeg
Deleted: attachments/301/57575.jpeg
Deleted: attachments/301/57826.jpeg
Deleted: attachments/301/57937.png
Deleted: attachments/301/57430.jpeg
Deleted: attachments/301/57248.png
Deleted: attachments/301/57415.heic
Deleted: attachments/301/57550.gif
Deleted: attachments/301/58423.jpg
Deleted: attachments/301/57943.jpeg
Deleted: attachments/301/57750.mov
Deleted: attachments/301/57410.jpeg
Deleted: attachments/301/58192.png
Deleted: attachments/301/58073.jpeg
Deleted: attachments/301/57739.jpeg
Deleted: attachments/301/57538.jpg
Deleted: attachments/301/58384.png
Deleted: attachments/301/58236.m4a
Deleted: attachments/301/58282.caf
Deleted: attachments/301/57423.heic
Deleted: attachments/301/58462.jpeg
Deleted: attachments/301/57778.jpeg
Deleted: attachments/301/57282.jpeg
Deleted: attachments/301/57406.jpeg
Deleted: attachments/301/57543.jpeg
Deleted: attachments/301/58435.jpeg
Deleted: attachments/301/57302.PNG
Deleted: attachments/301/57471.PNG
Deleted: attachments/301/57580.jpeg
Deleted: attachments/301/57703.jpeg
Deleted: attachments/301/57646.jpeg
Deleted: attachments/301/58419.jpeg
Deleted: attachments/301/57459.JPG
Deleted: attachments/301/58193.jpg
Deleted: attachments/301/57288.jpg
Deleted: attachments/301/57596.jpeg
Deleted: attachments/301/57345.JPEG
Deleted: attachments/301/58385.PNG
Deleted: attachments/301/57584.gif
Deleted: attachments/301/57938.jpeg
Deleted: attachments/301/57419.heic
Deleted: attachments/301/58458.jpeg
Deleted: attachments/301/57751.mov
Deleted: attachments/301/57418.heic
Deleted: attachments/301/58459.jpeg
Deleted: attachments/301/57939.jpeg
Deleted: attachments/301/57529.png
Deleted: attachments/301/57313.jpg
Deleted: attachments/301/57702.jpeg
Deleted: attachments/301/57647.jpeg
Deleted: attachments/301/58418.jpeg
Deleted: attachments/301/57639.caf
Deleted: attachments/301/58224.jpeg
Deleted: attachments/301/57539.jpeg
Deleted: attachments/301/58008.png
Deleted: attachments/301/57413.caf
Deleted: attachments/301/58064.jpeg
Deleted: attachments/301/58208.jpeg
Deleted: attachments/301/57407.jpeg
Deleted: attachments/301/57542.jpeg
Deleted: attachments/301/57422.heic
Deleted: attachments/301/58237.png
Deleted: attachments/301/57779.jpeg
Deleted: attachments/301/57283.jpeg
Deleted: attachments/301/57780.jpeg
Deleted: attachments/301/57514.jpg
Deleted: attachments/301/57919.png
Deleted: attachments/301/58072.jpeg
Deleted: attachments/301/57528.png
Deleted: attachments/301/57738.jpeg
Deleted: attachments/301/57272.PNG
Deleted: attachments/301/57942.jpeg
Deleted: attachments/301/57411.jpeg
Deleted: attachments/301/58182.PNG
Deleted: attachments/301/58433.jpg
Deleted: attachments/301/57466.jpeg
Deleted: attachments/301/58455.jpeg
Deleted: attachments/301/57414.heic
Deleted: attachments/301/57827.jpeg
Deleted: attachments/301/57431.jpeg
Deleted: attachments/301/57348.jpeg
Deleted: attachments/301/58369.png
Deleted: attachments/301/58228.jpeg
Deleted: attachments/301/58414.JPEG
Deleted: attachments/301/58290.jpeg
Deleted: attachments/301/57535.jpeg
Deleted: attachments/301/58235.jpg
Deleted: attachments/301/57923.jpeg
Deleted: attachments/301/58209.JPG
Deleted: attachments/301/58443.jpeg
Deleted: attachments/301/57338.PNG
Deleted: attachments/301/57463.PNG
Deleted: attachments/301/58341.jpeg
Deleted: attachments/301/57409.gif
Deleted: attachments/301/57479.heic
Deleted: attachments/301/57519.jpeg
Deleted: attachments/301/58316.jpeg
Deleted: attachments/301/57339.JPG
Deleted: attachments/301/58480.jpeg
Deleted: attachments/301/58300.jpeg
Deleted: attachments/301/58181.JPG
Deleted: attachments/301/58479.jpeg
Deleted: attachments/301/58183.jpeg
Deleted: attachments/301/57926.jpg
Deleted: attachments/301/57265.PNG
Deleted: attachments/301/57480.heic
Deleted: attachments/301/58091.jpeg
Deleted: attachments/34/57383.jpeg
Deleted: attachments/498/58039.jpg
Deleted: attachments/498/57629.jpeg
Deleted: attachments/498/57694.png
Deleted: attachments/498/57621.heic
Deleted: attachments/498/57969.heic
Deleted: attachments/498/58472.heic
Deleted: attachments/498/58099.png
Deleted: attachments/498/58216.jpeg
Deleted: attachments/498/57387.png
Deleted: attachments/498/58009.mov
Deleted: attachments/498/58012.mov
Deleted: attachments/498/58046.png
Deleted: attachments/498/57615.PNG
Deleted: attachments/498/57998.heic
Deleted: attachments/498/57979.png
Deleted: attachments/498/58252.jpeg
Deleted: attachments/498/57970.heic
Deleted: attachments/498/57971.heic
Deleted: attachments/498/57973.gif
Deleted: attachments/233/58473.heic
Deleted: attachments/233/57952.heic
Deleted: attachments/233/57834.mov
Deleted: attachments/233/58179.jpeg
Deleted: attachments/233/57568.heic
Deleted: attachments/233/58234.heic
Deleted: attachments/233/57954.mov
Deleted: attachments/233/57740.jpeg
Deleted: attachments/233/57732.HEIC
Deleted: attachments/233/57717.jpeg
Deleted: attachments/233/57724.heic
Deleted: attachments/233/57783.jpeg
Deleted: attachments/233/58415.jpg
Deleted: attachments/233/58002.heic
Deleted: attachments/233/57911.JPG
Deleted: attachments/233/57782.jpeg
Deleted: attachments/233/57832.mov
Deleted: attachments/233/57716.jpeg
Deleted: attachments/233/57910.JPG
Deleted: attachments/233/57741.jpeg
Deleted: attachments/233/57749.mov
Deleted: attachments/233/57986.heic
Deleted: attachments/233/58018.heic
Deleted: attachments/233/57953.heic
Deleted: attachments/233/57833.jpeg
Deleted: attachments/233/57838.jpeg
Deleted: attachments/233/57722.heic
Deleted: attachments/233/57785.jpeg
Deleted: attachments/233/57718.heic
Deleted: attachments/233/57947.jpeg
Deleted: attachments/233/58475.heic
Deleted: attachments/233/58025.heic
Deleted: attachments/233/58434.heic
Deleted: attachments/233/57840.mov
Deleted: attachments/233/57981.heic
Deleted: attachments/233/57312.heic
Deleted: attachments/233/57788.jpeg
Deleted: attachments/233/57955.heic
Deleted: attachments/233/57835.jpeg
Deleted: attachments/233/58474.heic
Deleted: attachments/233/58024.heic
Deleted: attachments/233/57386.heic
Deleted: attachments/233/57946.jpeg
Deleted: attachments/233/57719.heic
Deleted: attachments/233/57784.jpeg
Deleted: attachments/233/57723.heic
Deleted: attachments/233/57839.jpeg
Deleted: attachments/233/57277.heic
Deleted: attachments/233/58354.mov
Deleted: attachments/233/57787.jpeg
Deleted: attachments/233/57841.jpeg
Deleted: attachments/233/57777.heic
Deleted: attachments/233/58197.heic
Deleted: attachments/233/58355.heic
Deleted: attachments/233/57685.mov
Deleted: attachments/233/57686.heic
Deleted: attachments/233/58066.heic
Deleted: attachments/233/57836.jpeg
Deleted: attachments/233/57534.gif
Deleted: attachments/233/57837.jpeg

In [50]:
text_count['most_reacted_text'] = most_reacted_text

In [51]:
df.loc[df.reactions_received == df.reactions_received.max()].texts.to_string()

'dates\n2025-06-16 14:30:36    thats messed up ben'

In [52]:
text_count['ratio'] = (text_count['reactions_received'] / text_count['messages']).sort_values(ascending=False)

In [53]:
text_count[["texts", "image", "video", "reactions_received", "messages", "reactions_sent", "hahas_sent", "ratio", "word_count", "most_reacted_text"]].to_json('summarized-data.json', orient='index')

In [54]:
total = df.count().loc[['texts', 'image', 'video']].to_dict()

In [55]:
total['word_count'] = df.word_count.sum()

In [56]:
total["reactions_count"] = text_count.reactions_sent.sum()

In [57]:
total['most_reacted_text'] = df.loc[df['reactions_received'] == df.reactions_received.max()][['texts', 'image', 'video', 'reactions_received', 'sender']].to_dict(orient='records')

In [58]:
total

{'texts': 2319,
 'image': 351,
 'video': 20,
 'word_count': 16208,
 'reactions_count': 1777,
 'most_reacted_text': [{'texts': 'thats messed up ben',
   'image': 'attachments/301/57773.jpeg',
   'video': None,
   'reactions_received': 8,
   'sender': 'Austin'}]}

In [59]:
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)

In [60]:
with open('totals.json', 'w') as f:
    json.dump(total, f, cls=NpEncoder)

## This is where all of the formatting ends and the file has been outputted

In [61]:
text_count.sort_values(ascending=False, by='ratio')[['messages', 'reactions_received']]

                               messages  reactions_received
sender
+16138758948                          3                   9
Eden                                  2                   3
Greg                                 18                  19
Henry                                14                  14
Miklos                                2                   2
Ryan                                371                 356
John                                151                 136
Jack                                226                 165
Austin                              171                 117
Igor                                732                 463
Ben                                 330                 192
Darcy                               105                  61
Dan                                   9                   5
+16132612783                        249                 127
Nick                                132                  49
Mack                                 96                  35
Riley                                64                  22
Mel                                   3                   1
Michaela                              5                   1
hashtagyoloswagbeef@gmail.com         6                   0
Ali                                   1                   0

In [62]:
px.bar(text_count['ratio'].sort_values(ascending=False), title="Text-to-Reactions Received Ratio")

In [63]:
df.loc[df.sender == "Ali"].sort_values("reactions_received", ascending=False)[['texts', 'reactions_received']].values

array([['John sending his own joke to another chat', 0]], dtype=object)

In [64]:
df.loc[df.reactions_received.idxmax()]['reactions']

['Laughed by ryan.matson@icloud.com',
 'Laughed by +16138588921',
 'Laughed by +16134004076',
 'Laughed by +16133559273',
 'Laughed by +16138758948',
 'Laughed by +16048685587',
 'Laughed by itsjaxonmusic@gmail.com',
 'Laughed by Me']

In [65]:
px.line(
  df[(df.sender == 'Ryan 1') | (df.sender == 'Greg')], x=df[(df.sender == 'Ryan 1') | (df.sender == 'Greg')].index, y='word_count', color='sender',
  labels={'word_count' : 'Word Count', 'x' : 'Date'}
)

/Users/henrybrown/opt/anaconda3/envs/data_analysis/lib/python3.9/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result